[tool.poetry]
name = "cacher"
version = "0.1.0"
description = ""
authors = ["Matt Gibson <matt@doormatt.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
boltons = "^21.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
